### ISSUE TITLE
Translation hell

### ISSUE THREAD

**Issue by shlyakpavel** [lxqt/lxqt-organizer#24]
Could you please comment a reason you're using custom xml files instead of qt translation system?
https://github.com/lxqt/organizer/blob/4a8484706ea83f863c8219f12df616d05b40d5b3/src/mainwindow.cpp#L449 This way seems to be insane

**Comment by tsujan** [comment]
Translation is standardized in Qt for a long time and all LXQt apps do it according to Qt standards.

**Comment by ghost** [comment]
I have removed the xml file translation code so that the LXQt community can develop a qt translation system based on using lupdate, lrelease, QTranslator and QGuiTranslator. At the time of development there the were comments around Qt open source licensing issues (https://mail.kde.org/pipermail/kde-community/2020q2/006098.html) and so I developed a translation system which was independent of any tools which could potentially become proprietary. The removal of this xml file translation code will allow the LXQt community to develop an alternative approach.

**Comment by tsujan** [comment]
Will be archived.
